name: Build LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup workflow
        run: ./workflow-setup.sh

      - name: Build
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: make all

      - name: Publish PDFs
        uses: actions/upload-artifact@v7
        with:
          name: pdfs
          path: build/**/*.pdf
          if-no-files-found: error
