name: Build LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup workflow
        run: ./workflow-setup.sh

      - name: Build
        run: make all
